version: "3"

volumes:
  postgresql_data:
    driver: local

services:
  postgresql:
    image: bitnami/postgresql:latest
    environment:
      - POSTGRESQL_USERNAME=root
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=test
    ports:
      - 5432:5432
    volumes:
      - postgresql_data:/bitnami/postgresql
  adminer:
    image: adminer:latest
    environment:
      - ADMINER_DEFAULT_SERVER=localhost
    ports:
      - 8080:8080

